import { exec } from 'child_process';
import { promisify } from 'util';
import * as cheerio from 'cheerio';
import { logger, colors } from './logger.js';

const execAsync = promisify(exec);

/**
 * Mock Gemini API service for testing without an API key
 * Converts HTML to basic Markdown using cheerio
 */
class MockGeminiService {
  async convertHtmlToMarkdown(html, url) {
    console.log(colors.cyan('Using MOCK Gemini service'));
    const totalStart = Date.now();

    const parseStart = Date.now();
    const $ = cheerio.load(html);

    // Remove script and style tags
    $('script, style, nav, footer, aside').remove();

    // Try to find main content
    const mainContent = $('article, main, .content, #content, .post-content').first();
    const contentArea = mainContent.length > 0 ? mainContent : $('body');

    // Extract title
    let title = $('h1').first().text() || $('title').first().text() || 'Untitled Article';
    title = title.trim();
    const parseTime = Date.now() - parseStart;

    const processStart = Date.now();
    // Build markdown
    let markdown = `# ${title}\n\n`;

    // Extract paragraphs and headings
    contentArea.find('h1, h2, h3, h4, h5, h6, p, ul, ol, blockquote').each((i, elem) => {
      const tag = elem.name;
      const text = $(elem).text().trim();

      if (!text) return;

      switch(tag) {
        case 'h1':
          markdown += `# ${text}\n\n`;
          break;
        case 'h2':
          markdown += `## ${text}\n\n`;
          break;
        case 'h3':
          markdown += `### ${text}\n\n`;
          break;
        case 'h4':
          markdown += `#### ${text}\n\n`;
          break;
        case 'h5':
          markdown += `##### ${text}\n\n`;
          break;
        case 'h6':
          markdown += `###### ${text}\n\n`;
          break;
        case 'p':
          markdown += `${text}\n\n`;
          break;
        case 'blockquote':
          markdown += `> ${text}\n\n`;
          break;
        case 'ul':
        case 'ol':
          $(elem).find('li').each((j, li) => {
            const listText = $(li).text().trim();
            markdown += `- ${listText}\n`;
          });
          markdown += '\n';
          break;
      }
    });

    const processTime = Date.now() - processStart;
    const totalTime = Date.now() - totalStart;
    console.log(colors.dim(`Mock processing complete (parse: ${parseTime}ms, process: ${processTime}ms) | Total: ${totalTime}ms | Input: ${html.length} chars, Output: ${markdown.length} chars`));

    return markdown;
  }
}

/**
 * Real Gemini CLI service
 * Uses Gemini CLI tool to convert HTML to well-formatted Markdown
 */
class GeminiService {
  constructor(cliCommand = 'gemini') {
    this.cliCommand = cliCommand;
  }

  async convertHtmlToMarkdown(html, url) {
    console.log(colors.cyan('Using Gemini CLI tool'));
    const totalStart = Date.now();

    await logger.info('Starting Gemini CLI call', {
      url,
      htmlLength: html.length,
      timestamp: new Date().toISOString()
    });

    try {
      const promptStart = Date.now();
      const prompt = `Extract the main article content from this HTML and convert to clean Markdown.

Focus on: title, headings, paragraphs, lists, quotes, code blocks.
Ignore: navigation, ads, sidebars, comments, footers.

HTML (${html.length} chars):
${html.length > 50000 ? html.substring(0, 50000) + '\n\n[HTML truncated - too large]' : html}

Return only clean Markdown:`;
      const promptTime = Date.now() - promptStart;
      console.log(colors.dim(`Prompt prepared (${promptTime}ms, ${html.length} chars HTML)`));

      await logger.debug('Gemini CLI request details', {
        promptLength: prompt.length,
        htmlLength: html.length,
        truncated: html.length > 50000,
        cliCommand: this.cliCommand
      });

      const cliStart = Date.now();

      // Execute the Gemini CLI tool with the prompt
      // We pass the prompt via stdin to avoid shell escaping issues
      const { stdout, stderr } = await execAsync(this.cliCommand, {
        input: prompt,
        maxBuffer: 10 * 1024 * 1024, // 10MB buffer for large outputs
        timeout: 120000, // 2 minute timeout
        shell: true
      });

      const cliTime = Date.now() - cliStart;
      console.log(colors.success(`CLI call complete (${cliTime}ms)`));

      if (stderr) {
        await logger.warn('Gemini CLI stderr output', {
          url,
          stderr: stderr.trim()
        });
        console.log(colors.warning(`CLI warnings: ${stderr.trim()}`));
      }

      await logger.info('Gemini CLI success', {
        url,
        cliTime,
        outputSize: stdout.length
      });

      // Extract the generated text from CLI output
      const parseStart = Date.now();
      const generatedText = stdout.trim();

      if (!generatedText) {
        await logger.error('No content generated by Gemini CLI', {
          url,
          stdout,
          stderr
        });
        throw new Error('No content generated by Gemini CLI');
      }
      const parseTime = Date.now() - parseStart;
      const totalTime = Date.now() - totalStart;

      console.log(colors.dim(`Response parsed (${parseTime}ms) | Total: ${totalTime}ms | Output: ${generatedText.length} chars`));

      await logger.info('Gemini processing complete', {
        url,
        totalTime,
        outputLength: generatedText.length
      });

      return generatedText;

    } catch (error) {
      const totalTime = Date.now() - totalStart;

      await logger.error('Gemini CLI error', {
        url,
        error: error.message,
        code: error.code,
        stdout: error.stdout,
        stderr: error.stderr,
        totalTime
      });

      console.log(colors.error(`Error calling Gemini CLI: ${error.message}`));
      if (error.stderr) {
        console.log(colors.error(`CLI stderr: ${error.stderr}`));
      }
      throw error;
    }
  }
}

/**
 * Factory function to create the appropriate Gemini service
 */
export function createGeminiService(useMock = true, cliCommand = 'gemini') {
  if (useMock) {
    return new MockGeminiService();
  }

  if (!cliCommand) {
    throw new Error('GEMINI_CLI_COMMAND is required when not using mock service');
  }

  return new GeminiService(cliCommand);
}
