import axios from 'axios';
import * as cheerio from 'cheerio';

/**
 * Mock Gemini API service for testing without an API key
 * Converts HTML to basic Markdown using cheerio
 */
class MockGeminiService {
  async convertHtmlToMarkdown(html, url) {
    console.log('🧪 Using MOCK Gemini service');

    const $ = cheerio.load(html);

    // Remove script and style tags
    $('script, style, nav, footer, aside').remove();

    // Try to find main content
    const mainContent = $('article, main, .content, #content, .post-content').first();
    const contentArea = mainContent.length > 0 ? mainContent : $('body');

    // Extract title
    let title = $('h1').first().text() || $('title').first().text() || 'Untitled Article';
    title = title.trim();

    // Build markdown
    let markdown = `# ${title}\n\n`;
    markdown += `**Source:** ${url}\n\n---\n\n`;

    // Extract paragraphs and headings
    contentArea.find('h1, h2, h3, h4, h5, h6, p, ul, ol, blockquote').each((i, elem) => {
      const tag = elem.name;
      const text = $(elem).text().trim();

      if (!text) return;

      switch(tag) {
        case 'h1':
          markdown += `# ${text}\n\n`;
          break;
        case 'h2':
          markdown += `## ${text}\n\n`;
          break;
        case 'h3':
          markdown += `### ${text}\n\n`;
          break;
        case 'h4':
          markdown += `#### ${text}\n\n`;
          break;
        case 'h5':
          markdown += `##### ${text}\n\n`;
          break;
        case 'h6':
          markdown += `###### ${text}\n\n`;
          break;
        case 'p':
          markdown += `${text}\n\n`;
          break;
        case 'blockquote':
          markdown += `> ${text}\n\n`;
          break;
        case 'ul':
        case 'ol':
          $(elem).find('li').each((j, li) => {
            const listText = $(li).text().trim();
            markdown += `- ${listText}\n`;
          });
          markdown += '\n';
          break;
      }
    });

    return markdown;
  }
}

/**
 * Real Gemini API service
 * Uses Google's Gemini API to convert HTML to well-formatted Markdown
 */
class GeminiService {
  constructor(apiKey) {
    this.apiKey = apiKey;
    this.baseUrl = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent';
  }

  async convertHtmlToMarkdown(html, url) {
    console.log('🤖 Using real Gemini API');

    try {
      const prompt = `You are an expert at extracting the core content from web articles. Your task is to convert HTML into clean, readable Markdown focusing ONLY on the main article content.

EXTRACT:
- Article title (as h1)
- Main article body content (headings, paragraphs, lists, quotes)
- Important images with alt text (as markdown images)
- Code blocks and technical content
- Links within the article text
- Author and publication date if present

IGNORE/REMOVE:
- Navigation menus and headers
- Sidebars and widgets
- Advertisement blocks
- Comment sections
- "Related articles" or "You may also like" sections
- Social media share buttons
- Cookie banners and popups
- Footer content
- Newsletter signup forms
- Analytics scripts

OUTPUT FORMAT:
- Start with the article title as h1
- Add source URL on the second line
- Add a horizontal rule (---)
- Then the article content in clean, well-structured Markdown
- Preserve heading hierarchy (h1 → h2 → h3)
- Use proper Markdown for lists, quotes, code blocks, and emphasis

Source URL: ${url}

HTML Content:
${html}

Provide ONLY the Markdown output. No explanations, no meta-commentary, just the article in Markdown format.`;

      const response = await axios.post(
        `${this.baseUrl}?key=${this.apiKey}`,
        {
          contents: [{
            parts: [{
              text: prompt
            }]
          }]
        },
        {
          headers: {
            'Content-Type': 'application/json'
          }
        }
      );

      // Extract the generated text from Gemini's response
      const generatedText = response.data?.candidates?.[0]?.content?.parts?.[0]?.text;

      if (!generatedText) {
        throw new Error('No content generated by Gemini');
      }

      return generatedText;

    } catch (error) {
      console.error('Error calling Gemini API:', error.message);
      throw error;
    }
  }
}

/**
 * Factory function to create the appropriate Gemini service
 */
export function createGeminiService(useMock = true, apiKey = null) {
  if (useMock) {
    return new MockGeminiService();
  }

  if (!apiKey) {
    throw new Error('GEMINI_API_KEY is required when not using mock service');
  }

  return new GeminiService(apiKey);
}
