import axios from 'axios';
import * as cheerio from 'cheerio';
import { logger, colors } from './logger.js';

/**
 * Mock Gemini API service for testing without an API key
 * Converts HTML to basic Markdown using cheerio
 */
class MockGeminiService {
  async convertHtmlToMarkdown(html, url) {
    console.log(colors.cyan('Using MOCK Gemini service'));
    const totalStart = Date.now();

    const parseStart = Date.now();
    const $ = cheerio.load(html);

    // Remove script and style tags
    $('script, style, nav, footer, aside').remove();

    // Try to find main content
    const mainContent = $('article, main, .content, #content, .post-content').first();
    const contentArea = mainContent.length > 0 ? mainContent : $('body');

    // Extract title
    let title = $('h1').first().text() || $('title').first().text() || 'Untitled Article';
    title = title.trim();
    const parseTime = Date.now() - parseStart;

    const processStart = Date.now();
    // Build markdown
    let markdown = `# ${title}\n\n`;

    // Extract paragraphs and headings
    contentArea.find('h1, h2, h3, h4, h5, h6, p, ul, ol, blockquote').each((i, elem) => {
      const tag = elem.name;
      const text = $(elem).text().trim();

      if (!text) return;

      switch(tag) {
        case 'h1':
          markdown += `# ${text}\n\n`;
          break;
        case 'h2':
          markdown += `## ${text}\n\n`;
          break;
        case 'h3':
          markdown += `### ${text}\n\n`;
          break;
        case 'h4':
          markdown += `#### ${text}\n\n`;
          break;
        case 'h5':
          markdown += `##### ${text}\n\n`;
          break;
        case 'h6':
          markdown += `###### ${text}\n\n`;
          break;
        case 'p':
          markdown += `${text}\n\n`;
          break;
        case 'blockquote':
          markdown += `> ${text}\n\n`;
          break;
        case 'ul':
        case 'ol':
          $(elem).find('li').each((j, li) => {
            const listText = $(li).text().trim();
            markdown += `- ${listText}\n`;
          });
          markdown += '\n';
          break;
      }
    });

    const processTime = Date.now() - processStart;
    const totalTime = Date.now() - totalStart;
    console.log(colors.dim(`Mock processing complete (parse: ${parseTime}ms, process: ${processTime}ms) | Total: ${totalTime}ms | Input: ${html.length} chars, Output: ${markdown.length} chars`));

    return markdown;
  }
}

/**
 * Real Gemini API service
 * Uses Google's Gemini API to convert HTML to well-formatted Markdown
 */
class GeminiService {
  constructor(apiKey) {
    this.apiKey = apiKey;
    this.baseUrl = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent';
  }

  async convertHtmlToMarkdown(html, url, retryCount = 0) {
    console.log(colors.cyan('Using real Gemini API'));
    const totalStart = Date.now();

    await logger.info('Starting Gemini API call', {
      url,
      htmlLength: html.length,
      retryCount,
      timestamp: new Date().toISOString()
    });

    try {
      const promptStart = Date.now();
      const prompt = `Extract the main article content from this HTML and convert to clean Markdown.

Focus on: title, headings, paragraphs, lists, quotes, code blocks.
Ignore: navigation, ads, sidebars, comments, footers.

HTML (${html.length} chars):
${html.length > 50000 ? html.substring(0, 50000) + '\n\n[HTML truncated - too large]' : html}

Return only clean Markdown:`;
      const promptTime = Date.now() - promptStart;
      console.log(colors.dim(`Prompt prepared (${promptTime}ms, ${html.length} chars HTML)`));

      await logger.debug('Gemini request details', {
        promptLength: prompt.length,
        htmlLength: html.length,
        truncated: html.length > 50000,
        apiKey: this.apiKey ? 'present' : 'missing'
      });

      const apiStart = Date.now();
      const response = await axios.post(
        `${this.baseUrl}?key=${this.apiKey}`,
        {
          contents: [{
            parts: [{
              text: prompt
            }]
          }]
        },
        {
          headers: {
            'Content-Type': 'application/json'
          },
          timeout: 60000 // 60 second timeout
        }
      );
      const apiTime = Date.now() - apiStart;
      console.log(colors.success(`API call complete (${apiTime}ms)`));

      await logger.info('Gemini API success', {
        url,
        apiTime,
        responseStatus: response.status,
        responseSize: JSON.stringify(response.data).length
      });

      // Extract the generated text from Gemini's response
      const parseStart = Date.now();
      const generatedText = response.data?.candidates?.[0]?.content?.parts?.[0]?.text;

      if (!generatedText) {
        await logger.error('No content generated by Gemini', {
          url,
          responseData: response.data
        });
        throw new Error('No content generated by Gemini');
      }
      const parseTime = Date.now() - parseStart;
      const totalTime = Date.now() - totalStart;
      
      console.log(colors.dim(`Response parsed (${parseTime}ms) | Total: ${totalTime}ms | Output: ${generatedText.length} chars`));

      await logger.info('Gemini processing complete', {
        url,
        totalTime,
        outputLength: generatedText.length
      });

      return generatedText;

    } catch (error) {
      const totalTime = Date.now() - totalStart;
      
      await logger.error('Gemini API error', {
        url,
        error: error.message,
        status: error.response?.status,
        statusText: error.response?.statusText,
        headers: error.response?.headers,
        data: error.response?.data,
        totalTime,
        retryCount
      });

      // Handle rate limiting specifically
      if (error.response?.status === 429) {
        const errorData = error.response?.data?.error;
        let retryDelay = 60; // Default 60 seconds
        
        // Parse retry delay from Google's error response
        if (errorData?.details) {
          const retryInfo = errorData.details.find(d => d['@type']?.includes('RetryInfo'));
          if (retryInfo?.retryDelay) {
            // Parse delay like "48s" or "48.567136735s"
            const delayMatch = retryInfo.retryDelay.match(/(\d+(?:\.\d+)?)s?/);
            if (delayMatch) {
              retryDelay = Math.ceil(parseFloat(delayMatch[1]));
            }
          }
        }
        
        await logger.warn('Rate limit hit', {
          url,
          retryDelay,
          retryCount,
          errorDetails: errorData
        });
        
        // Retry up to 2 times with exponential backoff
        if (retryCount < 2) {
          console.log(colors.warning(`Rate limited (429) - Retrying in ${retryDelay}s (attempt ${retryCount + 1}/3)`));
          
          // Wait for the specified delay
          await new Promise(resolve => setTimeout(resolve, retryDelay * 1000));
          
          // Retry the request
          return this.convertHtmlToMarkdown(html, url, retryCount + 1);
        } else {
          console.log(colors.error(`Rate limited (429) - Max retries exceeded`));
        }
      }

      console.log(colors.error(`Error calling Gemini API: ${error.message}`));
      throw error;
    }
  }
}

/**
 * Factory function to create the appropriate Gemini service
 */
export function createGeminiService(useMock = true, apiKey = null) {
  if (useMock) {
    return new MockGeminiService();
  }

  if (!apiKey) {
    throw new Error('GEMINI_API_KEY is required when not using mock service');
  }

  return new GeminiService(apiKey);
}
